import { createHmac } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';

import { createGoClawWebhookClient } from './goclaw-client';

describe('GoClaw LLM webhook adapter', () => {
  it('uses the verified sync webhook contract with HMAC over exact bytes', async () => {
    const fetchImplementation = vi.fn(async (_url: string | URL | Request, _init?: RequestInit) =>
      new Response(JSON.stringify({ output: '  Tư vấn HTLabs  ' }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      }),
    );
    const signingKey = `wh_${'A'.repeat(39)}`;
    const client = createGoClawWebhookClient({
      baseUrl: 'https://goclaw.internal.example',
      webhookId: '0cfe8fb2-0f93-4da9-b7a3-e28d61be5efe',
      signingKey,
      contract: 'goclaw-webhook-llm-hmac-v1@2f3d68e',
      timeoutMs: 1_000,
      nowSeconds: () => 1_775_000_000,
      fetchImplementation,
    });

    await expect(client.reply({
      message: 'Xin chào',
      sessionKey: 'htlabs_solution_session',
      idempotencyKey: '4af89e0d-e5ff-4d98-8ba4-5b6528715305',
    })).resolves.toEqual({ message: 'Tư vấn HTLabs' });

    const [url, init] = fetchImplementation.mock.calls[0];
    expect(url).toBe('https://goclaw.internal.example/v1/webhooks/llm');
    expect(init?.method).toBe('POST');
    const body = String(init?.body);
    expect(JSON.parse(body)).toEqual({
      input: 'Xin chào',
      session_key: 'htlabs_solution_session',
      mode: 'sync',
      metadata: {
        source: 'htlabs-landing',
        request_id: '4af89e0d-e5ff-4d98-8ba4-5b6528715305',
      },
    });
    const expected = createHmac('sha256', Buffer.from(signingKey, 'utf8'))
      .update(`1775000000.${body}`)
      .digest('hex');
    expect(new Headers(init?.headers).get('x-goclaw-signature')).toBe(
      `t=1775000000,v1=${expected}`,
    );
    expect(new Headers(init?.headers).get('authorization')).toBeNull();
    expect(new Headers(init?.headers).get('idempotency-key')).toBe(
      '4af89e0d-e5ff-4d98-8ba4-5b6528715305',
    );
  });

  it('refuses an unpinned contract marker or non-HTTPS production URL', () => {
    const base = {
      webhookId: '0cfe8fb2-0f93-4da9-b7a3-e28d61be5efe',
      signingKey: `wh_${'A'.repeat(39)}`,
      timeoutMs: 1_000,
    };
    expect(() => createGoClawWebhookClient({
      ...base,
      baseUrl: 'https://goclaw.example',
      contract: 'latest',
    })).toThrow('invalid GoClaw contract');
    expect(() => createGoClawWebhookClient({
      ...base,
      baseUrl: 'http://goclaw.example',
      contract: 'goclaw-webhook-llm-hmac-v1@2f3d68e',
    })).toThrow('GoClaw URL must use HTTPS');
  });

  it('allows insecure HTTP only for an explicit loopback development client', () => {
    const base = {
      webhookId: '0cfe8fb2-0f93-4da9-b7a3-e28d61be5efe',
      signingKey: `wh_${'A'.repeat(39)}`,
      contract: 'goclaw-webhook-llm-hmac-v1@2f3d68e',
      timeoutMs: 1_000,
      allowInsecureLoopback: true,
    };
    expect(() => createGoClawWebhookClient({
      ...base,
      baseUrl: 'http://127.0.0.1:18790',
    })).not.toThrow();
    expect(() => createGoClawWebhookClient({
      ...base,
      baseUrl: 'http://goclaw.example',
    })).toThrow('GoClaw URL must use HTTPS');
  });

  it('accepts UUIDv7 webhook IDs generated by GoClaw', () => {
    expect(() => createGoClawWebhookClient({
      baseUrl: 'https://goclaw.example',
      webhookId: '019fcd95-aa6b-7247-9a43-c41c0f7fc724',
      signingKey: `wh_${'A'.repeat(39)}`,
      contract: 'goclaw-webhook-llm-hmac-v1@2f3d68e',
      timeoutMs: 1_000,
    })).not.toThrow();
  });

  it('maps timeout and malformed responses to privacy-safe upstream errors', async () => {
    const client = createGoClawWebhookClient({
      baseUrl: 'https://goclaw.example',
      webhookId: '0cfe8fb2-0f93-4da9-b7a3-e28d61be5efe',
      signingKey: `wh_${'A'.repeat(39)}`,
      contract: 'goclaw-webhook-llm-hmac-v1@2f3d68e',
      timeoutMs: 10,
      fetchImplementation: vi.fn(async (_url, init) => {
        await new Promise((_resolve, reject) => {
          init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')));
        });
        return new Response();
      }),
    });
    await expect(client.reply({
      message: 'secret prompt',
      sessionKey: 's',
      idempotencyKey: '4af89e0d-e5ff-4d98-8ba4-5b6528715305',
    }))
      .rejects.toMatchObject({ code: 'UPSTREAM_TIMEOUT' });
  });
});
